steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/chunaavai-c1dda/chunaavai:latest'
      - '.'
    timeout: '900s'

images:
  - 'gcr.io/chunaavai-c1dda/chunaavai:latest'

timeout: '1200s'
